spring:

  main:
    banner-mode: off

  sql:
    init.mode: always

  jpa:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true

  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/shareit"
    username: "dbuser"
    password: "12345"

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: trace